name: Test, Build, and Publish Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  test-build-and-publish-pypi:
    name: Test, Build and publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.6'
    - name: Install build and publish dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Install test dependencies and package
      run: |
        pip install -r requirements.txt
    - name: Run tests with pytest
      run: |
        pytest
    - name: Build package
      run: python -m build
    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
